In [2]:
pwd

'/Users/gemunu/kaggle/kaggle_insu'

In [255]:
cd kaggle_insu

[Errno 2] No such file or directory: 'kaggle_insu'
/Users/gemunu/kaggle_insu

In [406]:
ls

insure.ipynb               sample_submission.csv.zip  test.csv.zip
kag_insu.py                sub.csv                    train.csv.zip

In [407]:
import pandas as pd
import zipfile
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
%matplotlib inline
from matplotlib import pyplot as plt

zf=zipfile.ZipFile('train.csv.zip')
zft=zipfile.ZipFile('test.csv.zip')
train=pd.read_csv(zf.open('train.csv'))
test=pd.read_csv(zft.open('test.csv'))

In [262]:
for i in range(len(train.columns)):
    print (train[train.columns[i]].describe(),test[test.columns[i]].describe())

count    59381.000000
mean     39507.211515
std      22815.883089
min          2.000000
25%      19780.000000
50%      39487.000000
75%      59211.000000
max      79146.000000
Name: Id, dtype: float64 count    19765.000000
mean     39772.653883
std      22942.157493
min          1.000000
25%      19792.000000
50%      39898.000000
75%      59758.000000
max      79129.000000
Name: Id, dtype: float64
count    59381.000000
mean         1.026355
std          0.160191
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: Product_Info_1, dtype: float64 count    19765.000000
mean         1.024994
std          0.156110
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: Product_Info_1, dtype: float64
count     59381
unique       19
top          D3
freq      14321
Name: Product_Info_2, dtype: object count     19765
unique       19
top          D3
freq       4432
Name: Product_Info_2, dtype: object
count    59381.000000
mean        24.415655
std          5.072885
min          1.000000
25%         26.000000
50%         26.000000
75%         26.000000
max         38.000000
Name: Product_Info_3, dtype: float64 count    19765.000000
mean        24.321730
std          5.184879
min          2.000000
25%         26.000000
50%         26.000000
75%         26.000000
max         37.000000
Name: Product_Info_3, dtype: float64
count    59381.000000
mean         0.328952
std          0.282562
min          0.000000
25%          0.076923
50%          0.230769
75%          0.487179
max          1.000000
Name: Product_Info_4, dtype: float64 count    19765.000000
mean         0.324381
std          0.279439
min          0.000000
25%          0.076923
50%          0.230769
75%          0.487179
max          1.000000
Name: Product_Info_4, dtype: float64
count    59381.000000
mean         2.006955
std          0.083107
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Product_Info_5, dtype: float64 count    19765.000000
mean         2.006527
std          0.080526
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Product_Info_5, dtype: float64
count    59381.000000
mean         2.673599
std          0.739103
min          1.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Product_Info_6, dtype: float64 count    19765.000000
mean         2.655755
std          0.754993
min          1.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Product_Info_6, dtype: float64
count    59381.000000
mean         1.043583
std          0.291949
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Product_Info_7, dtype: float64 count    19765.000000
mean         1.043410
std          0.291445
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Product_Info_7, dtype: float64
count    59381.000000
mean         0.405567
std          0.197190
min          0.000000
25%          0.238806
50%          0.402985
75%          0.567164
max          1.000000
Name: Ins_Age, dtype: float64 count    19765.000000
mean         0.414901
std          0.200997
min          0.000000
25%          0.253731
50%          0.417910
75%          0.582090
max          0.970149
Name: Ins_Age, dtype: float64
count    59381.000000
mean         0.707283
std          0.074239
min          0.000000
25%          0.654545
50%          0.709091
75%          0.763636
max          1.000000
Name: Ht, dtype: float64 count    19765.000000
mean         0.705846
std          0.074497
min          0.345455
25%          0.654545
50%          0.709091
75%          0.763636
max          1.000000
Name: Ht, dtype: float64
count    59381.000000
mean         0.292587
std          0.089037
min          0.000000
25%          0.225941
50%          0.288703
75%          0.345188
max          1.000000
Name: Wt, dtype: float64 count    19765.000000
mean         0.292557
std          0.090343
min          0.083682
25%          0.225941
50%          0.288703
75%          0.345188
max          0.878661
Name: Wt, dtype: float64
count    59381.000000
mean         0.469462
std          0.122213
min          0.000000
25%          0.385517
50%          0.451349
75%          0.532858
max          1.000000
Name: BMI, dtype: float64 count    19765.000000
mean         0.470708
std          0.123423
min          0.096503
25%          0.384703
50%          0.454472
75%          0.534485
max          1.000000
Name: BMI, dtype: float64
count    59362.000000
mean         0.077582
std          0.082347
min          0.000000
25%          0.035000
50%          0.060000
75%          0.100000
max          1.000000
Name: Employment_Info_1, dtype: float64 count    19762.000000
mean         0.078975
std          0.083927
min          0.000000
25%          0.035000
50%          0.060000
75%          0.100000
max          1.000000
Name: Employment_Info_1, dtype: float64
count    59381.000000
mean         8.641821
std          4.227082
min          1.000000
25%          9.000000
50%          9.000000
75%          9.000000
max         38.000000
Name: Employment_Info_2, dtype: float64 count    19765.000000
mean         8.443612
std          4.189177
min          1.000000
25%          9.000000
50%          9.000000
75%          9.000000
max         37.000000
Name: Employment_Info_2, dtype: float64
count    59381.000000
mean         1.300904
std          0.715034
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Employment_Info_3, dtype: float64 count    19765.000000
mean         1.325525
std          0.738316
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Employment_Info_3, dtype: float64
count    52602.000000
mean         0.006283
std          0.032816
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Employment_Info_4, dtype: float64 count    17628.000000
mean         0.006513
std          0.034962
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Employment_Info_4, dtype: float64
count    59381.000000
mean         2.142958
std          0.350033
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Employment_Info_5, dtype: float64 count    19765.000000
mean         2.149051
std          0.356148
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Employment_Info_5, dtype: float64
count    48527.000000
mean         0.361469
std          0.349551
min          0.000000
25%          0.060000
50%          0.250000
75%          0.550000
max          1.000000
Name: Employment_Info_6, dtype: float64 count    15978.000000
mean         0.368569
std          0.353681
min          0.000000
25%          0.055000
50%          0.250000
75%          0.600000
max          1.000000
Name: Employment_Info_6, dtype: float64
count    59381.000000
mean         1.209326
std          0.417939
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: InsuredInfo_1, dtype: float64 count    19765.000000
mean         1.204098
std          0.414317
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: InsuredInfo_1, dtype: float64
count    59381.000000
mean         2.007427
std          0.085858
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: InsuredInfo_2, dtype: float64 count    19765.000000
mean         2.007387
std          0.085631
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: InsuredInfo_2, dtype: float64
count    59381.000000
mean         5.835840
std          2.674536
min          1.000000
25%          3.000000
50%          6.000000
75%          8.000000
max         11.000000
Name: InsuredInfo_3, dtype: float64 count    19765.000000
mean         5.695573
std          2.976492
min          1.000000
25%          3.000000
50%          8.000000
75%          8.000000
max         11.000000
Name: InsuredInfo_3, dtype: float64
count    59381.000000
mean         2.883666
std          0.320627
min          2.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: InsuredInfo_4, dtype: float64 count    19765.000000
mean         2.892639
std          0.309580
min          2.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: InsuredInfo_4, dtype: float64
count    59381.000000
mean         1.027180
std          0.231566
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: InsuredInfo_5, dtype: float64 count    19765.000000
mean         1.030053
std          0.243323
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: InsuredInfo_5, dtype: float64
count    59381.000000
mean         1.409188
std          0.491688
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          2.000000
Name: InsuredInfo_6, dtype: float64 count    19765.000000
mean         1.420946
std          0.493723
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          2.000000
Name: InsuredInfo_6, dtype: float64
count    59381.000000
mean         1.038531
std          0.274915
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: InsuredInfo_7, dtype: float64 count    19765.000000
mean         1.033190
std          0.255503
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: InsuredInfo_7, dtype: float64
count    59381.000000
mean         1.727606
std          0.445195
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: Insurance_History_1, dtype: float64 count    19765.000000
mean         1.706299
std          0.455468
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: Insurance_History_1, dtype: float64
count    59381.000000
mean         1.055792
std          0.329328
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Insurance_History_2, dtype: float64 count    19765.000000
mean         1.049380
std          0.310366
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Insurance_History_2, dtype: float64
count    59381.000000
mean         2.146983
std          0.989139
min          1.000000
25%          1.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Insurance_History_3, dtype: float64 count    19765.000000
mean         2.183405
std          0.983062
min          1.000000
25%          1.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Insurance_History_3, dtype: float64
count    59381.000000
mean         1.958707
std          0.945739
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Insurance_History_4, dtype: float64 count    19765.000000
mean         1.916671
std          0.946017
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Insurance_History_4, dtype: float64
count    33985.000000
mean         0.001733
std          0.007338
min          0.000000
25%          0.000400
50%          0.000973
75%          0.002000
max          1.000000
Name: Insurance_History_5, dtype: float64 count    11660.000000
mean         0.001642
std          0.002581
min          0.000000
25%          0.000373
50%          0.000833
75%          0.002000
max          0.131415
Name: Insurance_History_5, dtype: float64
count    59381.000000
mean         1.901989
std          0.971223
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max          3.000000
Name: Insurance_History_7, dtype: float64 count    19765.000000
mean         1.891424
std          0.956846
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max          3.000000
Name: Insurance_History_7, dtype: float64
count    59381.000000
mean         2.048484
std          0.755149
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Insurance_History_8, dtype: float64 count    19765.00000
mean         2.03744
std          0.76777
min          1.00000
25%          1.00000
50%          2.00000
75%          3.00000
max          3.00000
Name: Insurance_History_8, dtype: float64
count    59381.000000
mean         2.419360
std          0.509577
min          1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Insurance_History_9, dtype: float64 count    19765.000000
mean         2.398583
std          0.511058
min          1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Insurance_History_9, dtype: float64
count    59381.000000
mean         2.686230
std          0.483159
min          1.000000
25%          2.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Family_Hist_1, dtype: float64 count    19765.000000
mean         2.687731
std          0.482264
min          1.000000
25%          2.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Family_Hist_1, dtype: float64
count    30725.000000
mean         0.474550
std          0.154959
min          0.000000
25%          0.362319
50%          0.463768
75%          0.579710
max          1.000000
Name: Family_Hist_2, dtype: float64 count    9885.000000
mean        0.474566
std         0.155105
min         0.043478
25%         0.362319
50%         0.463768
75%         0.579710
max         0.942029
Name: Family_Hist_2, dtype: float64
count    25140.000000
mean         0.497737
std          0.140187
min          0.000000
25%          0.401961
50%          0.519608
75%          0.598039
max          1.000000
Name: Family_Hist_3, dtype: float64 count    8701.000000
mean        0.499983
std         0.140092
min         0.000000
25%         0.411765
50%         0.519608
75%         0.607843
max         0.892157
Name: Family_Hist_3, dtype: float64
count    40197.000000
mean         0.444890
std          0.163012
min          0.000000
25%          0.323944
50%          0.422535
75%          0.563380
max          0.943662
Name: Family_Hist_4, dtype: float64 count    13088.000000
mean         0.446715
std          0.164719
min          0.000000
25%          0.323944
50%          0.436620
75%          0.563380
max          1.000000
Name: Family_Hist_4, dtype: float64
count    17570.000000
mean         0.484635
std          0.129200
min          0.000000
25%          0.401786
50%          0.508929
75%          0.580357
max          1.000000
Name: Family_Hist_5, dtype: float64 count    6141.000000
mean        0.492239
std         0.128967
min         0.026786
25%         0.419643
50%         0.517857
75%         0.589286
max         0.848214
Name: Family_Hist_5, dtype: float64
count    50492.000000
mean         7.962172
std         13.027697
min          0.000000
25%          2.000000
50%          4.000000
75%          9.000000
max        240.000000
Name: Medical_History_1, dtype: float64 count    16793.000000
mean         7.827547
std         12.561432
min          0.000000
25%          2.000000
50%          4.000000
75%          9.000000
max        235.000000
Name: Medical_History_1, dtype: float64
count    59381.000000
mean       253.987100
std        178.621154
min          1.000000
25%        112.000000
50%        162.000000
75%        418.000000
max        648.000000
Name: Medical_History_2, dtype: float64 count    19765.000000
mean       249.794637
std        177.943542
min          1.000000
25%        112.000000
50%        162.000000
75%        407.000000
max        647.000000
Name: Medical_History_2, dtype: float64
count    59381.000000
mean         2.102171
std          0.303098
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_3, dtype: float64 count    19765.000000
mean         2.147331
std          0.354445
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_3, dtype: float64
count    59381.000000
mean         1.654873
std          0.475414
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: Medical_History_4, dtype: float64 count    19765.000000
mean         1.658740
std          0.474144
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: Medical_History_4, dtype: float64
count    59381.000000
mean         1.007359
std          0.085864
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: Medical_History_5, dtype: float64 count    19765.000000
mean         1.007488
std          0.086211
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: Medical_History_5, dtype: float64
count    59381.000000
mean         2.889897
std          0.456128
min          1.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Medical_History_6, dtype: float64 count    19765.000000
mean         2.887174
std          0.461446
min          1.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Medical_History_6, dtype: float64
count    59381.000000
mean         2.012277
std          0.172360
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_7, dtype: float64 count    19765.000000
mean         2.012598
std          0.171582
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_7, dtype: float64
count    59381.000000
mean         2.044088
std          0.291353
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_8, dtype: float64 count    19765.000000
mean         2.044118
std          0.291165
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_8, dtype: float64
count    59381.000000
mean         1.769943
std          0.421032
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: Medical_History_9, dtype: float64 count    19765.000000
mean         1.775816
std          0.417054
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: Medical_History_9, dtype: float64
count    557.000000
mean     141.118492
std      107.759559
min        0.000000
25%        8.000000
50%      229.000000
75%      240.000000
max      240.000000

IndexError: index 127 is out of bounds for axis 0 with size 127

In [ ]:
train.Family_Hist_1

In [12]:
train.Medical_History_10.mode()

0    240
dtype: float64

In [267]:
temp1=[]
for i in test.columns:
    if (test[i].describe()[0]) != 19765:
        print (i,test[i].dtype,test[i].describe()[0])
        temp1.append(i)

In [ ]:
#temp=[]
for i in train.columns:
    if (train[i].describe()[0]) != 59381:
        print (i,train[i].dtype,train[i].describe()[0])
        #temp.append(i)

In [10]:
meds=['Medical_History_1','Medical_History_10','Medical_History_24','Medical_History_32','Medical_History_15']

In [11]:
for i in meds:
    temp1.remove(i)

In [ ]:
meds

In [ ]:
train.drop('Insurance_History_5',axis=1,inplace=True)
#test.drop('Medical_History_24',axis=1,inplace=True)
#test.drop('Medical_History_32',axis=1,inplace=True)

In [ ]:
train.drop('Medical_History_10',axis=1,inplace=True)
#train.drop('Medical_History_24',axis=1,inplace=True)
#train.drop('Medical_History_32',axis=1,inplace=True)

In [ ]:
#temp1.remove('Insurance_History_5')
temp1.remove('Medical_History_10')
temp.remove('Medical_History_10')
#temp.remove('Insurance_History_5')

In [ ]:
train.drop('Medical_History_10',axis=1,inplace=True)
test.drop('Medical_History_10',axis=1,inplace=True)

In [265]:
for i in temp1:
    men=-1.#train[i].mean()
    test[i].fillna(men,inplace=True)

In [266]:
test

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_39,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48
0,1,1,D3,26,0.487179,2,3,1,0.611940,0.781818,...,0,0,0,0,0,0,0,0,0,0
1,3,1,A2,26,0.076923,2,3,1,0.626866,0.727273,...,0,0,0,0,0,0,0,0,0,0
2,4,1,D3,26,0.144667,2,3,1,0.582090,0.709091,...,0,0,0,0,0,0,0,0,0,0
3,9,1,A1,26,0.151709,2,1,1,0.522388,0.654545,...,0,0,0,0,0,0,0,0,1,1
4,12,1,A1,26,0.076923,2,3,1,0.298507,0.672727,...,0,0,0,0,0,0,0,0,0,0
5,13,1,D3,26,0.230769,2,3,1,0.567164,0.818182,...,0,0,0,0,0,0,0,0,0,0
6,21,1,A3,26,1.000000,2,3,1,0.298507,0.690909,...,0,0,0,0,0,0,0,0,0,0
7,28,1,D4,26,0.256410,2,3,1,0.059701,0.654545,...,0,0,0,0,0,0,0,0,0,0
8,30,1,D3,26,0.076923,2,3,1,0.611940,0.618182,...,0,0,0,0,0,0,0,0,0,0
9,36,1,A3,26,0.076923,2,3,1,0.328358,0.781818,...,0,0,0,0,0,0,0,0,0,0
10,38,1,D4,26,1.000000,2,3,1,0.313433,0.763636,...,0,0,0,0,0,0,0,0,0,0
11,43,1,D1,29,0.384615,2,3,1,0.656716,0.709091,...,0,0,0,0,0,0,0,0,0,0
12,45,1,E1,26,0.230769,2,3,1,0.194030,0.709091,...,0,0,0,0,0,1,0,0,0,0
13,48,1,D1,26,0.179487,2,3,1,0.253731,0.636364,...,0,0,0,0,0,0,0,0,0,0
14,50,1,D1,26,0.076923,2,3,1,0.179104,0.745455,...,0,0,0,0,0,0,0,0,0,0
15,51,1,E1,26,0.158974,2,3,1,0.462687,0.854545,...,0,0,0,0,0,0,0,0,0,0
16,54,1,A2,26,0.076923,2,1,1,0.582090,0.600000,...,0,0,0,0,0,0,0,0,0,0
17,55,1,D4,26,0.230769,2,1,1,0.194030,0.763636,...,0,0,0,0,0,0,0,0,0,0
18,59,1,D3,26,0.487179,2,1,1,0.208955,0.636364,...,0,0,0,0,0,0,0,0,0,0
19,62,1,A8,26,0.076923,2,3,1,0.656716,0.618182,...,0,0,0,1,0,0,0,0,0,0
20,63,1,D4,26,0.487179,2,3,1,0.373134,0.636364,...,0,0,0,0,0,0,0,0,0,0
21,66,1,D4,26,0.461538,2,3,3,0.119403,0.763636,...,0,0,0,0,0,0,0,0,0,0
22,69,1,D3,26,1.000000,2,1,1,0.328358,0.800000,...,0,0,0,0,0,0,0,0,0,0
23,82,1,D3,10,0.230769,2,1,1,0.313433,0.672727,...,0,0,0,0,0,0,0,0,0,0
24,83,1,D3,26,0.282051,2,3,3,0.507463,0.763636,...,0,0,0,0,0,0,0,0,0,0
25,84,1,D2,29,0.487179,2,3,1,0.522388,0.727273,...,0,0,0,1,0,0,0,0,0,0
26,86,1,D3,26,0.435897,2,3,1,0.567164,0.545455,...,0,0,0,0,0,0,0,0,0,0
27,89,1,A6,26,0.230769,2,3,1,0.432836,0.709091,...,0,0,0,0,0,0,0,0,0,0
28,90,1,A8,26,0.230769,2,1,1,0.656716,0.872727,...,0,0,0,0,0,0,0,0,0,0
29,92,2,D2,15,0.076923,2,3,1,0.059701,0.636364,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19735,79004,1,D4,26,0.743590,2,3,1,0.373134,0.763636,...,0,0,0,0,0,0,0,0,0,0
19736,79007,1,D3,10,0.076923,2,3,1,0.328358,0.636364,...,0,0,0,0,0,0,0,0,0,0
19737,79020,1,D3,29,0.230769,2,3,1,0.597015,0.727273,...,0,0,0,0,0,0,0,0,0,0
19738,79022,1,D2,26,0.076923,2,3,1,0.761194,0.581818,...,0,0,0,0,0,0,0,0,0,0
19739,79027,1,A1,26,0.487179,2,1,3,0.537313,0.763636,...,0,0,0,0,0,0,0,0,0,0
19740,79028,1,D3,26,0.589744,2,3,1,0.179104,0.563636,...,0,0,0,0,0,0,0,0,0,0
19741,79031,1,A2,26,0.076923,2,3,1,0.656716,0.672727,...,0,0,0,0,0,0,0,0,0,0
19742,79035,1,D1,26,1.000000,2,3,3,0.641791,0.800000,...,0,0,0,0,0,0,0,0,0,0
19743,79038,1,A6,26,1.000000,2,3,1,0.402985,0.672727,...,0,0,0,0,0,0,0,0,0,0
19744,79047,1,B2,26,0.487179,2,1,1,0.283582,0.600000,...,0,0,0,0,0,0,0,0,0,0
19745,79048,1,E1,26,0.179487,2,3,1,0.417910,0.636364,...,0,0,0,0,0,0,0,0,0,0
19746,79051,1,D3,26,1.000000,2,3,1,0.164179,0.781818,...,0,0,0,0,0,0,0,0,0,0
19747,79054,1,A8,29,0.025641,2,3,1,0.776119,0.818182,...,0,0,0,0,0,0,0,0,0,0
19748,79060,1,D3,26,0.589744,2,3,1,0.402985,0.763636,...,0,0,0,0,0,0,0,0,0,0
19749,79064,1,D2,26,0.076923,2,3,1,0.671642,0.727273,...,0,0,0,1,0,0,0,0,0,0
19750,79065,1,D1,26,0.487179,2,1,3,0.492537,0.781818,...,0,0,0,0,0,0,0,0,0,0
19751,79067,1,D4,26,0.076923,2,3,1,0.477612,0.727273,...,0,0,0,0,0,0,0,0,0,0
19752,79071,1,D2,26,0.230769,2,3,1,0.597015,0.690909,...,0,0,0,0,0,0,0,0,0,0
19753,79072,1,A5,26,0.292440,2,3,1,0.522388,0.745455,...,0,0,0,0,0,0,0,0,0,0
19754,79073,1,D4,26,0.179487,2,3,1,0.477612,0.690909,...,0,0,0,0,0,0,0,0,0,0
19755,79080,1,D3,26,0.169231,2,3,1,0.432836,0.854545,...,0,0,0,0,1,0,0,0,0,0
19756,79083,1,D2,26,1.000000,2,3,1,0.462687,0.672727,...,0,0,0,0,0,0,0,0,0,1
19757,79084,2,D4,26,0.487179,2,1,1,0.268657,0.781818,...,0,0,0,0,0,0,0,0,0,0
19758,79085,1,D4,26,0.487179,2,3,3,0.313433,0.763636,...,0,0,0,0,0,0,0,0,0,0
19759,79089,1,D4,26,0.487179,2,3,1,0.179104,0.672727,...,0,0,0,0,0,0,0,0,0,0
19760,79093,1,D3,26,0.128205,2,3,1,0.537313,0.636364,...,0,0,0,0,0,0,0,0,0,0
19761,79099,1,D4,10,0.230769,2,3,1,0.134328,0.618182,...,0,0,0,0,0,0,0,0,0,0
19762,79102,1,A2,26,0.076923,2,3,1,0.850746,0.727273,...,0,0,0,0,0,0,0,0,0,0
19763,79125,1,D1,26,0.487179,2,3,1,0.522388,0.745455,...,0,0,0,0,0,0,0,0,0,0
19764,79129,1,D3,26,1.000000,2,1,1,0.343284,0.781818,...,0,0,0,0,0,0,0,0,0,0

In [25]:
for i in meds:
    mo=test[i].mode()[0]
    print (i,mo)
    test[i].fillna(mo,inplace=True)

Medical_History_1 1.0
Medical_History_10 240.0
Medical_History_24 0.0
Medical_History_32 0.0
Medical_History_15 240.0

In [ ]:
test.Medical_History_15.fillna(240,inplace=True)
train.Medical_History_15.fillna(240,inplace=True)

In [268]:
y=train.pop('Response')

ids=test.pop('Id')

train.drop('Id',axis=1,inplace=True)

In [ ]:
train['Medical_History_10']

In [ ]:
sns.distplot(train['Ht'])

In [274]:
le=LabelEncoder()
train['Product_Info_2']=le.fit_transform(train['Product_Info_2'])
test['Product_Info_2']=le.fit_transform(test['Product_Info_2'])

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca=PCA(2)

In [ ]:
test_project=pca.fit_transform(test)
print (train_project.shape)

In [ ]:
plt.scatter(train_project[:,0],train_project[:,1],edgecolors=None,alpha=.5,cmap=plt.cm.get_cmap('nipy_spectral',1000))
plt.colorbar;

In [ ]:
pca=PCA(15).fit(test)
plt.plot(np.cumsum(pca.explained_variance_ratio_))

In [ ]:
pctest=pca.transform(test)
pctest.shape

In [ ]:
train.head()

In [ ]:
ipct=pca.inverse_transform(pct)

In [38]:
test.head()

,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,...,Medical_Keyword_39,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48
0,1,16,26,0.487179,2,3,1,0.611940,0.781818,0.338912,...,0,0,0,0,0,0,0,0,0,0
1,1,1,26,0.076923,2,3,1,0.626866,0.727273,0.311715,...,0,0,0,0,0,0,0,0,0,0
2,1,16,26,0.144667,2,3,1,0.582090,0.709091,0.320084,...,0,0,0,0,0,0,0,0,0,0
3,1,0,26,0.151709,2,1,1,0.522388,0.654545,0.267782,...,0,0,0,0,0,0,0,0,1,1
4,1,0,26,0.076923,2,3,1,0.298507,0.672727,0.246862,...,0,0,0,0,0,0,0,0,0,0

In [277]:
import xgboost as xgb

In [278]:
dtrain=xgb.DMatrix(train,label=y,missing=-1.)

In [279]:
dtest=xgb.DMatrix(test,missing=-1.)

In [646]:
param = {'bst:max_depth':9, 'bst:eta':0.7, 'silent':1, 'objective':'multi:softmax','num_class':9}
param["colsample_bytree"] = 0.30
param["subsample"] = 0.60
param["min_child_weight"] = 1
param['nthread'] = 4
plst=list(param.items())

In [647]:
%%time
bst=xgb.train(plst,dtrain,num_boost_round=100)
bst_pred=bst.predict(dtest)
#print (eval_wrapper(y,bstpred))

KeyboardInterrupt:

In [628]:
bst_pred=bst_pred.tolist()

In [629]:
type(bst_pred)

list

In [630]:
for i in range(len(bst_pred)):
    bst_pred[i].pop(0)

In [650]:
bst_pred[0]

[0.17242521047592163,
 0.2110598236322403,
 1.195397817355115e-05,
 0.00030605087522417307,
 0.0009651171276345849,
 0.5437421798706055,
 0.02527318336069584,
 0.04619990289211273]

In [483]:
evallist  = [(y,'eval'), (dtrain,'train')]

In [440]:
from ml_metrics import quadratic_weighted_kappa

def eval_wrapper(yhat, y):  
    y = np.array(y)
    y = y.astype(int)
    yhat = np.array(yhat)
    yhat = np.clip(np.round(yhat), np.min(y), np.max(y)).astype(int)   
    return quadratic_weighted_kappa(yhat, y)

In [296]:
%%time
bst=xgb.sklearn.XGBClassifier(max_depth=7,n_estimators=200,learning_rate=0.05,objective='multi:softmax',subsample=0.6,missing=-1.,colsample_bytree=0.3,min_child_weight=40)
bst.fit(train,y)

CPU times: user 4min 42s, sys: 1.16 s, total: 4min 43s
Wall time: 4min 44s

In [492]:
%%time
bst=xgb.train(plst,dtrain,num_boost_round=10)

CPU times: user 14.6 s, sys: 200 ms, total: 14.8 s
Wall time: 15 s

In [484]:
%%time
bst=xgb.train(plst,dtrain,num_boost_round=80)

CPU times: user 1min 59s, sys: 566 ms, total: 2min
Wall time: 2min

In [577]:
eval_wrapper(y,bstpred)

0.7050990547634736

In [578]:
bstpred=bst.predict(dtrain)
#eval_wrapper(y,bstpred)

0.7050990547634736

In [468]:
eval_wrapper(y,bstpred)

0.540330604542377

In [346]:
lab * bst_pred1

array([[ 0.36322168,  0.38870466,  0.00802026, ...,  0.89774546,
         1.63948689,  0.21976268],
       [ 0.09828941,  0.13401854,  0.02439685, ...,  1.15241325,
         1.03252853,  3.45518708],
       [ 0.08563572,  0.20036916,  0.03321282, ...,  2.05749249,
         1.56580363,  1.40778077],
       ...,
       [ 0.28730476,  0.30453086,  0.02959301, ...,  1.94615597,
         0.44608894,  0.03587934],
       [ 0.1136587 ,  1.05598629,  0.01634585, ...,  0.29347238,
         0.09876351,  0.15046293],
       [ 0.13586645,  0.32869846,  0.6686317 , ...,  1.0926877 ,
         0.22066687,  0.04558828]])

In [656]:
resps=[]
for i in range(len(bst_pred)):
    max_p=[]
    for j in range(8):
        max_p.append((bst_pred[i][j]+bc_pred[i][j])+rfc_pred[i][j]/3)
    #print (max_p)
    resps.append(max_p.index(max(max_p))+1)

In [642]:
resps1

[8,
 1,
 8,
 8,
 8,
 8,
 8,
 7,
 7,
 6,
 7,
 6,
 1,
 8,
 6,
 5,
 7,
 8,
 6,
 8,
 8,
 6,
 2,
 8,
 6,
 7,
 8,
 8,
 6,
 8,
 6,
 2,
 6,
 2,
 2,
 1,
 8,
 7,
 1,
 2,
 6,
 6,
 1,
 8,
 6,
 2,
 8,
 6,
 5,
 5,
 8,
 6,
 7,
 1,
 7,
 5,
 6,
 6,
 8,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 8,
 8,
 6,
 6,
 8,
 8,
 8,
 7,
 7,
 8,
 6,
 6,
 6,
 7,
 6,
 1,
 2,
 7,
 6,
 1,
 8,
 5,
 6,
 8,
 6,
 6,
 1,
 8,
 6,
 6,
 6,
 5,
 8,
 8,
 1,
 6,
 7,
 2,
 8,
 8,
 2,
 2,
 2,
 8,
 8,
 6,
 6,
 8,
 8,
 7,
 8,
 5,
 5,
 6,
 8,
 8,
 8,
 8,
 7,
 6,
 2,
 8,
 1,
 2,
 6,
 6,
 6,
 8,
 6,
 8,
 8,
 2,
 8,
 5,
 1,
 7,
 8,
 8,
 8,
 6,
 6,
 8,
 5,
 2,
 6,
 6,
 6,
 7,
 8,
 8,
 7,
 6,
 6,
 6,
 4,
 1,
 8,
 7,
 8,
 6,
 2,
 7,
 8,
 2,
 8,
 8,
 6,
 8,
 8,
 2,
 8,
 6,
 8,
 8,
 6,
 8,
 8,
 8,
 6,
 5,
 6,
 1,
 6,
 7,
 6,
 2,
 1,
 8,
 6,
 5,
 8,
 8,
 8,
 8,
 6,
 8,
 8,
 7,
 6,
 8,
 1,
 7,
 2,
 8,
 8,
 7,
 6,
 6,
 8,
 8,
 2,
 8,
 2,
 8,
 6,
 2,
 8,
 1,
 7,
 5,
 6,
 6,
 6,
 8,
 6,
 8,
 7,
 8,
 8,
 8,
 8,
 2,
 7,
 1,
 6,
 2,
 8,
 6,
 6,
 8,
 8,
 8,
 6,
 7,
 8,
 8,
 5,
 8,
 6,
 8,
 6,
 6,
 8,
 6,
 8,
 7,
 1,
 7,
 6,
 7,
 8,
 7,
 8,
 8,
 6,
 7,
 8,
 8,
 2,
 6,
 7,
 2,
 6,
 8,
 1,
 2,
 8,
 6,
 6,
 8,
 7,
 2,
 8,
 8,
 8,
 6,
 8,
 6,
 8,
 5,
 8,
 8,
 6,
 6,
 8,
 8,
 7,
 8,
 8,
 1,
 6,
 8,
 8,
 2,
 6,
 1,
 5,
 6,
 2,
 6,
 6,
 1,
 8,
 5,
 8,
 2,
 6,
 6,
 8,
 7,
 8,
 8,
 7,
 1,
 5,
 6,
 8,
 6,
 5,
 7,
 2,
 1,
 5,
 6,
 7,
 8,
 8,
 8,
 1,
 6,
 6,
 8,
 6,
 8,
 8,
 6,
 5,
 8,
 1,
 8,
 8,
 6,
 8,
 8,
 8,
 8,
 1,
 6,
 5,
 1,
 8,
 8,
 6,
 8,
 8,
 8,
 6,
 8,
 6,
 7,
 1,
 8,
 6,
 6,
 6,
 6,
 1,
 5,
 6,
 5,
 8,
 8,
 8,
 7,
 5,
 6,
 6,
 5,
 8,
 6,
 8,
 8,
 2,
 6,
 1,
 6,
 8,
 6,
 8,
 6,
 7,
 8,
 8,
 6,
 2,
 6,
 7,
 6,
 6,
 8,
 8,
 2,
 6,
 6,
 7,
 6,
 2,
 6,
 8,
 6,
 7,
 8,
 8,
 6,
 6,
 6,
 8,
 6,
 8,
 5,
 1,
 6,
 8,
 7,
 2,
 8,
 1,
 6,
 6,
 8,
 6,
 6,
 8,
 7,
 6,
 6,
 1,
 2,
 8,
 8,
 8,
 8,
 6,
 8,
 6,
 8,
 8,
 7,
 8,
 8,
 6,
 7,
 2,
 7,
 6,
 8,
 8,
 6,
 6,
 8,
 1,
 7,
 8,
 8,
 6,
 1,
 1,
 6,
 2,
 8,
 6,
 8,
 8,
 8,
 6,
 6,
 8,
 5,
 2,
 7,
 6,
 8,
 6,
 5,
 5,
 8,
 8,
 2,
 6,
 2,
 7,
 8,
 8,
 2,
 1,
 8,
 6,
 8,
 1,
 8,
 8,
 8,
 2,
 5,
 7,
 8,
 7,
 1,
 7,
 5,
 8,
 6,
 1,
 1,
 7,
 5,
 1,
 6,
 5,
 6,
 8,
 8,
 6,
 6,
 2,
 6,
 6,
 2,
 8,
 6,
 8,
 8,
 6,
 8,
 8,
 2,
 6,
 8,
 2,
 6,
 6,
 6,
 2,
 5,
 7,
 6,
 8,
 6,
 6,
 8,
 8,
 7,
 6,
 5,
 8,
 6,
 6,
 8,
 8,
 1,
 7,
 2,
 7,
 8,
 8,
 6,
 8,
 7,
 8,
 8,
 6,
 7,
 6,
 6,
 8,
 6,
 6,
 8,
 8,
 6,
 6,
 8,
 6,
 8,
 8,
 6,
 6,
 8,
 8,
 2,
 6,
 8,
 5,
 8,
 8,
 6,
 8,
 8,
 8,
 7,
 8,
 5,
 8,
 8,
 8,
 6,
 6,
 7,
 8,
 8,
 1,
 6,
 2,
 2,
 8,
 8,
 7,
 8,
 2,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 7,
 8,
 8,
 6,
 5,
 7,
 7,
 6,
 6,
 2,
 8,
 8,
 7,
 8,
 1,
 1,
 2,
 6,
 8,
 2,
 8,
 1,
 6,
 8,
 1,
 8,
 8,
 8,
 8,
 8,
 1,
 7,
 8,
 5,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 6,
 4,
 6,
 6,
 2,
 8,
 5,
 8,
 8,
 5,
 8,
 6,
 6,
 8,
 6,
 8,
 6,
 8,
 8,
 8,
 2,
 8,
 6,
 8,
 6,
 6,
 8,
 8,
 2,
 6,
 8,
 6,
 6,
 1,
 8,
 5,
 8,
 8,
 5,
 8,
 7,
 6,
 7,
 8,
 6,
 8,
 6,
 8,
 7,
 8,
 7,
 6,
 8,
 6,
 8,
 8,
 6,
 1,
 5,
 8,
 2,
 8,
 1,
 1,
 8,
 8,
 7,
 7,
 6,
 8,
 1,
 6,
 2,
 6,
 8,
 8,
 8,
 1,
 6,
 6,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 8,
 8,
 2,
 7,
 8,
 2,
 8,
 8,
 8,
 2,
 8,
 6,
 1,
 2,
 7,
 6,
 1,
 8,
 8,
 8,
 6,
 5,
 2,
 7,
 8,
 8,
 6,
 6,
 8,
 8,
 8,
 2,
 6,
 8,
 2,
 6,
 8,
 1,
 2,
 6,
 6,
 2,
 6,
 6,
 6,
 6,
 2,
 8,
 6,
 7,
 6,
 8,
 6,
 8,
 2,
 5,
 6,
 8,
 8,
 8,
 7,
 2,
 8,
 8,
 2,
 8,
 7,
 8,
 6,
 8,
 8,
 7,
 8,
 6,
 6,
 8,
 8,
 6,
 8,
 2,
 8,
 1,
 8,
 8,
 8,
 8,
 8,
 2,
 6,
 1,
 6,
 8,
 6,
 6,
 8,
 8,
 8,
 8,
 6,
 8,
 2,
 8,
 5,
 6,
 8,
 1,
 8,
 7,
 1,
 8,
 1,
 5,
 8,
 6,
 2,
 7,
 6,
 6,
 2,
 7,
 8,
 8,
 8,
 6,
 8,
 8,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 7,
 2,
 1,
 7,
 6,
 1,
 6,
 8,
 6,
 8,
 8,
 8,
 6,
 5,
 6,
 8,
 6,
 6,
 2,
 8,
 6,
 6,
 6,
 6,
 8,
 8,
 1,
 2,
 8,
 8,
 8,
 6,
 8,
 7,
 8,
 1,
 6,
 6,
 5,
 1,
 5,
 6,
 7,
 6,
 2,
 6,
 8,
 8,
 7,
 6,
 8,
 1,
 8,
 8,
 6,
 2,
 8,
 6,
 6,
 6,
 7,
 8,
 6,
 6,
 2,
 6,
 8,
 1,
 8,
 6,
 8,
 7,
 7,
 8,
 1,
 6,
 2,
 6,
 6,
 7,
 7,
 7,
 8,
 6,
 8,
 8,
 2,
 2,
 6,
 7,
 8,
 6,
 6,
 2,
 8,
 8,
 ...]

In [655]:
resps1=[]
for i in range(len(bst_pred)):
    max_p=[]
    for j in range(8):
        max_p.append((bst_pred[i][j]*bc_pred[i][j])*rfc_pred[i][j])
    #print (max_p)
    max_p=[i/sum(max_p) for i in max_p]
    resps1.append(max_p.index(max(max_p))+1)

In [430]:
pd.DataFrame(resps1,resps)

    0
7   7
8   8
7   7
8   8
8   8
8   8
8   8
8   8
7   7
8   8
8   8
8   8
4   4
8   8
7   7
8   8
7   7
8   8
8   8
2   2
8   8
8   8
8   8
8   8
6   6
7   7
8   8
8   8
2   2
8   8
.. ..
7   8
8   8
2   2
2   2
6   7
8   8
8   8
2   2
8   8
6   6
6   6
6   6
5   2
6   6
2   2
6   6
8   8
2   2
6   6
8   8
6   6
2   2
8   8
6   6
8   8
8   8
8   8
6   6
2   2
3   2

[19765 rows x 1 columns]

In [546]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import BaggingClassifier

from sklearn.ensemble import RandomForestRegressor,BaggingRegressor
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.pipeline import Pipeline

from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

In [ ]:
import sklearn
sklearn.__version__

In [ ]:
import xg

In [572]:
%%time
rfc=RandomForestClassifier(n_estimators=600,max_depth=9,criterion='entropy',max_features=0.33)
rfc.fit(train,y)
#bc=Pipeline([('f_s',SelectFromModel(LinearSVC(penalty="l1"))),('c_f',RandomForestClassifier(n_estimators=100))])

CPU times: user 2min 31s, sys: 926 ms, total: 2min 31s
Wall time: 2min 32s

In [568]:
%%time
bc=GradientBoostingClassifier(n_estimators=100,max_features=0.33)
bc.fit(train,y)

CPU times: user 6min 1s, sys: 19.4 s, total: 6min 21s
Wall time: 6min 23s

In [ ]:
from sklearn.cross_validation import cross_val_score

In [ ]:
cross_val_score(bc,train,y).mean()

In [ ]:
bc.fit(train,y)

In [ ]:
model=SelectFromModel(bc,prefit=True,threshold='0.1*mean')

In [ ]:
train_new.columns.difference(test.columns)

In [653]:
bc_pred=bc.predict_proba(test)

In [654]:
bc_pred

array([[ 0.32136545,  0.20803549,  0.00141907, ...,  0.1338581 ,
         0.27271545,  0.03868091],
       [ 0.08699306,  0.07952239,  0.00329953, ...,  0.24067206,
         0.18569086,  0.35749415],
       [ 0.10723286,  0.0953784 ,  0.00490348, ...,  0.35720449,
         0.24843455,  0.13433975],
       ...,
       [ 0.28113399,  0.11943277,  0.0063551 , ...,  0.28335517,
         0.05963092,  0.00624822],
       [ 0.08613305,  0.59541727,  0.00128712, ...,  0.05058632,
         0.00851711,  0.01575032],
       [ 0.07187606,  0.07976108,  0.2736246 , ...,  0.26607553,
         0.09521898,  0.00570946]])

In [571]:
eval_wrapper(y,bcpred)

0.5548542315889684

In [ ]:
train_new=model.transform(train)

In [ ]:
train.Medical_Keyword_40

In [657]:
k=[i for i,j in zip(resps1,resps) if i!=j]

In [1]:
len(k)

NameError: name 'k' is not defined

In [ ]:
imp_feats=pd.Series(bc.feature_importances_,index=train.columns)
imp_feats.sort()
imp_feats.plot(kind='barh')

In [ ]:
sorted(zip(map(lambda x: round(x, 4), bc.feature_importances_), train.columns), 
             reverse=True)

In [ ]:
sorted(zip(map(lambda x: round(x, 4), bc.feature_importances_), train.columns), 
             reverse=True)

In [111]:
import numpy as np

In [248]:
bst_pred1=bst_pred1.astype(int)

In [639]:
resps

[8,
 4,
 6,
 8,
 8,
 8,
 8,
 7,
 8,
 6,
 8,
 8,
 7,
 8,
 8,
 5,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 7,
 8,
 8,
 6,
 8,
 4,
 2,
 6,
 8,
 3,
 4,
 8,
 8,
 1,
 8,
 6,
 1,
 8,
 8,
 1,
 3,
 8,
 6,
 8,
 5,
 8,
 6,
 7,
 8,
 4,
 5,
 6,
 6,
 8,
 6,
 5,
 6,
 6,
 6,
 8,
 6,
 8,
 8,
 6,
 6,
 8,
 8,
 8,
 1,
 7,
 8,
 8,
 8,
 6,
 8,
 8,
 5,
 4,
 6,
 6,
 8,
 8,
 2,
 6,
 8,
 6,
 6,
 1,
 8,
 6,
 6,
 6,
 5,
 8,
 8,
 8,
 6,
 7,
 8,
 8,
 8,
 8,
 2,
 2,
 7,
 8,
 6,
 6,
 8,
 8,
 8,
 8,
 5,
 5,
 6,
 8,
 8,
 8,
 8,
 7,
 8,
 5,
 8,
 8,
 2,
 5,
 8,
 6,
 8,
 8,
 8,
 8,
 2,
 8,
 5,
 6,
 7,
 8,
 8,
 8,
 6,
 5,
 8,
 5,
 2,
 6,
 6,
 7,
 8,
 8,
 8,
 7,
 6,
 5,
 6,
 4,
 8,
 8,
 7,
 8,
 8,
 8,
 7,
 8,
 5,
 8,
 8,
 8,
 8,
 8,
 2,
 8,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 5,
 6,
 4,
 6,
 7,
 6,
 2,
 5,
 8,
 6,
 5,
 8,
 8,
 8,
 8,
 8,
 8,
 7,
 7,
 8,
 8,
 5,
 7,
 2,
 8,
 8,
 1,
 6,
 8,
 8,
 8,
 8,
 8,
 2,
 8,
 6,
 8,
 8,
 4,
 7,
 5,
 1,
 6,
 6,
 8,
 8,
 8,
 7,
 8,
 8,
 8,
 8,
 2,
 7,
 1,
 6,
 2,
 8,
 6,
 6,
 8,
 1,
 8,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 8,
 6,
 8,
 7,
 1,
 8,
 6,
 7,
 7,
 7,
 8,
 8,
 6,
 7,
 8,
 8,
 4,
 6,
 7,
 2,
 8,
 8,
 1,
 2,
 8,
 6,
 8,
 8,
 8,
 7,
 8,
 8,
 8,
 6,
 8,
 6,
 8,
 5,
 8,
 8,
 6,
 6,
 8,
 8,
 7,
 8,
 8,
 8,
 6,
 8,
 8,
 8,
 8,
 5,
 5,
 1,
 2,
 6,
 4,
 2,
 8,
 5,
 7,
 8,
 6,
 8,
 8,
 7,
 8,
 8,
 7,
 4,
 8,
 1,
 8,
 6,
 5,
 8,
 2,
 1,
 5,
 6,
 8,
 8,
 8,
 8,
 1,
 8,
 6,
 8,
 7,
 8,
 8,
 6,
 5,
 8,
 1,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 1,
 5,
 5,
 7,
 8,
 8,
 6,
 8,
 8,
 8,
 6,
 8,
 6,
 8,
 8,
 8,
 6,
 6,
 6,
 6,
 8,
 5,
 6,
 5,
 8,
 5,
 8,
 8,
 5,
 6,
 6,
 5,
 8,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 6,
 8,
 8,
 8,
 6,
 2,
 6,
 8,
 8,
 5,
 4,
 8,
 8,
 6,
 6,
 7,
 8,
 7,
 3,
 8,
 6,
 8,
 8,
 6,
 4,
 6,
 8,
 8,
 8,
 8,
 5,
 1,
 6,
 8,
 7,
 8,
 8,
 8,
 7,
 4,
 8,
 6,
 8,
 8,
 7,
 8,
 6,
 1,
 8,
 8,
 8,
 8,
 6,
 6,
 8,
 6,
 8,
 8,
 8,
 8,
 8,
 2,
 7,
 4,
 7,
 8,
 5,
 8,
 6,
 6,
 8,
 1,
 7,
 8,
 8,
 6,
 1,
 1,
 6,
 2,
 8,
 8,
 5,
 8,
 6,
 6,
 8,
 8,
 8,
 2,
 7,
 6,
 8,
 6,
 5,
 5,
 8,
 8,
 2,
 6,
 2,
 8,
 8,
 8,
 2,
 7,
 8,
 1,
 8,
 7,
 8,
 8,
 8,
 4,
 8,
 7,
 8,
 7,
 1,
 7,
 5,
 8,
 8,
 1,
 8,
 8,
 8,
 8,
 5,
 5,
 6,
 8,
 8,
 8,
 6,
 5,
 6,
 5,
 8,
 8,
 8,
 8,
 8,
 7,
 8,
 8,
 2,
 3,
 8,
 2,
 6,
 6,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 8,
 7,
 6,
 8,
 8,
 8,
 6,
 6,
 8,
 2,
 7,
 8,
 8,
 8,
 8,
 6,
 8,
 7,
 8,
 8,
 7,
 2,
 6,
 6,
 8,
 8,
 8,
 8,
 8,
 6,
 6,
 2,
 6,
 8,
 8,
 6,
 6,
 8,
 8,
 4,
 6,
 8,
 5,
 8,
 6,
 6,
 8,
 8,
 8,
 8,
 8,
 5,
 8,
 8,
 8,
 6,
 6,
 7,
 8,
 8,
 5,
 6,
 8,
 2,
 8,
 8,
 7,
 8,
 2,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 2,
 8,
 8,
 7,
 8,
 1,
 1,
 2,
 6,
 8,
 5,
 8,
 1,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 7,
 8,
 5,
 8,
 8,
 8,
 8,
 1,
 4,
 4,
 6,
 4,
 6,
 6,
 2,
 8,
 5,
 8,
 8,
 6,
 8,
 6,
 5,
 8,
 6,
 8,
 6,
 8,
 8,
 8,
 2,
 8,
 6,
 8,
 5,
 6,
 8,
 8,
 2,
 6,
 8,
 5,
 6,
 8,
 8,
 5,
 8,
 8,
 5,
 8,
 7,
 6,
 7,
 8,
 6,
 8,
 5,
 8,
 7,
 8,
 7,
 8,
 8,
 6,
 4,
 8,
 3,
 8,
 5,
 8,
 2,
 8,
 1,
 1,
 8,
 8,
 8,
 7,
 6,
 8,
 8,
 1,
 2,
 6,
 4,
 8,
 8,
 1,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 8,
 5,
 8,
 8,
 8,
 8,
 8,
 8,
 2,
 8,
 6,
 1,
 6,
 8,
 6,
 5,
 8,
 8,
 8,
 1,
 5,
 2,
 7,
 8,
 5,
 6,
 8,
 8,
 8,
 8,
 2,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 6,
 8,
 6,
 2,
 8,
 6,
 2,
 8,
 8,
 7,
 8,
 8,
 6,
 8,
 2,
 5,
 5,
 8,
 8,
 8,
 8,
 2,
 8,
 8,
 2,
 8,
 7,
 8,
 8,
 8,
 8,
 7,
 8,
 8,
 6,
 8,
 8,
 8,
 8,
 2,
 5,
 7,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 1,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 6,
 8,
 5,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 1,
 5,
 8,
 6,
 2,
 7,
 2,
 6,
 8,
 7,
 8,
 8,
 8,
 6,
 8,
 8,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 3,
 7,
 5,
 8,
 7,
 6,
 1,
 6,
 8,
 4,
 8,
 8,
 2,
 6,
 6,
 8,
 8,
 5,
 8,
 2,
 8,
 6,
 2,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 8,
 2,
 8,
 1,
 7,
 6,
 5,
 8,
 5,
 7,
 8,
 7,
 8,
 8,
 8,
 8,
 7,
 7,
 7,
 8,
 8,
 8,
 6,
 3,
 8,
 5,
 6,
 6,
 7,
 8,
 6,
 8,
 8,
 1,
 8,
 8,
 8,
 6,
 8,
 8,
 7,
 8,
 8,
 6,
 8,
 6,
 6,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 6,
 6,
 2,
 8,
 8,
 ...]

In [659]:
sub = pd.DataFrame(np.column_stack((ids, resps1)), columns=['Id', 'Response'])
sub.to_csv('sub.csv',index=False)
pd.read_csv('sub.csv')

          Id  Response
0          1         6
1          3         8
2          4         6
3          9         8
4         12         8
5         13         8
6         21         8
7         28         8
8         30         7
9         36         8
10        38         8
11        43         8
12        45         4
13        48         8
14        50         6
15        51         8
16        54         7
17        55         8
18        59         8
19        62         6
20        63         8
21        66         8
22        69         8
23        82         8
24        83         6
25        84         7
26        86         8
27        89         8
28        90         1
29        92         8
...      ...       ...
19735  79004         7
19736  79007         8
19737  79020         2
19738  79022         1
19739  79027         6
19740  79028         8
19741  79031         8
19742  79035         2
19743  79038         8
19744  79047         6
19745  79048         6
19746  79051         6
19747  79054         5
19748  79060         6
19749  79064         2
19750  79065         5
19751  79067         8
19752  79071         2
19753  79072         6
19754  79073         8
19755  79080         6
19756  79083         2
19757  79084         8
19758  79085         6
19759  79089         8
19760  79093         8
19761  79099         8
19762  79102         6
19763  79125         2
19764  79129         4

[19765 rows x 2 columns]

In [211]:
x=[1,2,3,4]
y=[1,5,2,1]

,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,...,Medical_Keyword_39,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48
0,1,16,10,0.076923,2,1,1,0.641791,0.581818,0.148536,...,0,0,0,0,0,0,0,0,0,0
1,1,0,26,0.076923,2,3,1,0.059701,0.600000,0.131799,...,0,0,0,0,0,0,0,0,0,0
2,1,18,26,0.076923,2,3,1,0.029851,0.745455,0.288703,...,0,0,0,0,0,0,0,0,0,0
3,1,17,10,0.487179,2,3,1,0.164179,0.672727,0.205021,...,0,0,0,0,0,0,0,0,0,0
4,1,15,26,0.230769,2,3,1,0.417910,0.654545,0.234310,...,0,0,0,0,0,0,0,0,0,0
5,1,15,26,0.230769,3,1,1,0.507463,0.836364,0.299163,...,0,0,0,0,0,0,0,0,0,0
6,1,7,10,0.166194,2,3,1,0.373134,0.581818,0.173640,...,0,0,0,0,0,0,0,0,0,0
7,1,15,26,0.076923,2,3,1,0.611940,0.781818,0.403766,...,0,0,0,0,0,0,0,0,0,0
8,1,16,26,0.230769,2,3,1,0.522388,0.618182,0.184100,...,0,0,0,0,0,0,0,0,0,0
9,1,18,21,0.076923,2,3,1,0.552239,0.600000,0.284519,...,0,0,0,0,0,0,0,0,0,0
10,1,16,26,0.128205,2,3,1,0.537313,0.690909,0.309623,...,0,0,0,0,0,1,0,0,1,1
11,1,17,26,0.230769,2,3,1,0.298507,0.690909,0.271967,...,0,0,0,0,0,0,0,0,0,0
12,1,1,26,0.102564,2,3,1,0.567164,0.618182,0.163180,...,0,0,0,0,0,0,0,0,0,0
13,2,14,26,0.487179,2,3,1,0.223881,0.781818,0.361925,...,0,0,0,0,0,0,0,0,0,0
14,1,17,26,0.487179,2,3,1,0.328358,0.636364,0.142259,...,0,0,0,0,0,0,0,0,0,0
15,1,6,26,0.000000,2,3,1,0.626866,0.672727,0.330544,...,0,0,0,0,0,0,0,0,0,0
16,2,17,26,0.487179,2,3,1,0.208955,0.745455,0.246862,...,0,1,0,0,0,0,0,0,0,0
17,1,16,26,0.384615,2,3,1,0.268657,0.636364,0.228033,...,0,0,0,0,0,0,0,0,0,0
18,1,16,26,0.076923,2,3,1,0.388060,0.781818,0.309623,...,0,0,0,0,0,0,0,0,0,0
19,1,17,26,0.487179,2,3,1,0.223881,0.600000,0.138075,...,0,0,0,0,0,0,0,0,0,0
20,1,15,26,0.435897,2,3,1,0.388060,0.745455,0.246862,...,0,0,0,0,0,0,0,0,0,0
21,1,0,26,1.000000,2,1,1,0.537313,0.709091,0.370293,...,0,0,0,0,0,0,0,0,0,0
22,1,17,26,0.230769,2,3,1,0.179104,0.800000,0.539749,...,0,0,0,0,0,0,0,0,0,0
23,1,1,26,0.179487,2,3,1,0.164179,0.745455,0.288703,...,0,0,0,0,0,0,0,0,0,0
24,1,14,26,0.487179,2,1,1,0.164179,0.818182,0.435146,...,0,0,0,0,0,0,0,0,0,0
25,1,5,26,0.230769,2,3,1,0.268657,0.781818,0.368201,...,0,0,0,0,0,0,0,0,0,0
26,1,0,26,1.000000,2,3,1,0.507463,0.654545,0.299163,...,0,0,0,0,0,0,0,0,0,0
27,1,16,26,0.230769,2,3,1,0.134328,0.763636,0.215481,...,0,0,0,0,0,0,0,0,0,0
28,1,17,26,0.487179,2,3,1,0.492537,0.618182,0.276151,...,0,0,0,0,0,0,0,0,0,0
29,1,16,26,1.000000,2,3,1,0.582090,0.654545,0.278243,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19735,1,17,26,0.743590,2,3,1,0.373134,0.763636,0.355649,...,0,0,0,0,0,0,0,0,0,0
19736,1,16,10,0.076923,2,3,1,0.328358,0.636364,0.267782,...,0,0,0,0,0,0,0,0,0,0
19737,1,16,29,0.230769,2,3,1,0.597015,0.727273,0.288703,...,0,0,0,0,0,0,0,0,0,0
19738,1,15,26,0.076923,2,3,1,0.761194,0.581818,0.167364,...,0,0,0,0,0,0,0,0,0,0
19739,1,0,26,0.487179,2,1,3,0.537313,0.763636,0.292887,...,0,0,0,0,0,0,0,0,0,0
19740,1,16,26,0.589744,2,3,1,0.179104,0.563636,0.150628,...,0,0,0,0,0,0,0,0,0,0
19741,1,1,26,0.076923,2,3,1,0.656716,0.672727,0.278243,...,0,0,0,0,0,0,0,0,0,0
19742,1,14,26,1.000000,2,3,3,0.641791,0.800000,0.456067,...,0,0,0,0,0,0,0,0,0,0
19743,1,5,26,1.000000,2,3,1,0.402985,0.672727,0.173640,...,0,0,0,0,0,0,0,0,0,0
19744,1,9,26,0.487179,2,1,1,0.283582,0.600000,0.152720,...,0,0,0,0,0,0,0,0,0,0
19745,1,18,26,0.179487,2,3,1,0.417910,0.636364,0.341004,...,0,0,0,0,0,0,0,0,0,0
19746,1,16,26,1.000000,2,3,1,0.164179,0.781818,0.215481,...,0,0,0,0,0,0,0,0,0,0
19747,1,7,29,0.025641,2,3,1,0.776119,0.818182,0.414226,...,0,0,0,0,0,0,0,0,0,0
19748,1,16,26,0.589744,2,3,1,0.402985,0.763636,0.372385,...,0,0,0,0,0,0,0,0,0,0
19749,1,15,26,0.076923,2,3,1,0.671642,0.727273,0.230126,...,0,0,0,1,0,0,0,0,0,0
19750,1,14,26,0.487179,2,1,3,0.492537,0.781818,0.476987,...,0,0,0,0,0,0,0,0,0,0
19751,1,17,26,0.076923,2,3,1,0.477612,0.727273,0.267782,...,0,0,0,0,0,0,0,0,0,0
19752,1,15,26,0.230769,2,3,1,0.597015,0.690909,0.372385,...,0,0,0,0,0,0,0,0,0,0
19753,1,4,26,0.292440,2,3,1,0.522388,0.745455,0.278243,...,0,0,0,0,0,0,0,0,0,0
19754,1,17,26,0.179487,2,3,1,0.477612,0.690909,0.161088,...,0,0,0,0,0,0,0,0,0,0
19755,1,16,26,0.169231,2,3,1,0.432836,0.854545,0.414226,...,0,0,0,0,1,0,0,0,0,0
19756,1,15,26,1.000000,2,3,1,0.462687,0.672727,0.410042,...,0,0,0,0,0,0,0,0,0,1
19757,2,17,26,0.487179,2,1,1,0.268657,0.781818,0.309623,...,0,0,0,0,0,0,0,0,0,0
19758,1,17,26,0.487179,2,3,3,0.313433,0.763636,0.393305,...,0,0,0,0,0,0,0,0,0,0
19759,1,17,26,0.487179,2,3,1,0.179104,0.672727,0.246862,...,0,0,0,0,0,0,0,0,0,0
19760,1,16,26,0.128205,2,3,1,0.537313,0.636364,0.152720,...,0,0,0,0,0,0,0,0,0,0
19761,1,17,10,0.230769,2,3,1,0.134328,0.618182,0.225941,...,0,0,0,0,0,0,0,0,0,0
19762,1,1,26,0.076923,2,3,1,0.850746,0.727273,0.414226,...,0,0,0,0,0,0,0,0,0,0
19763,1,14,26,0.487179,2,3,1,0.522388,0.745455,0.529289,...,0,0,0,0,0,0,0,0,0,0
19764,1,16,26,1.000000,2,1,1,0.343284,0.781818,0.382845,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
x=train.copy()

In [ ]:
x['res']=y

In [ ]:
temp

In [ ]:
x.columns

In [ ]:
import seaborn as sns

In [ ]:
sns.countplot(x['res'])

In [ ]:
%matplotlib inline

In [ ]:
from  matplotlib import pyplot as plt

In [ ]:
import fig_